CommunityPortal/Areas/Admin/Models/ViewModels/Post/CreatePostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CommunityPortal.Areas.Admin.Models.ViewModels.Post
{
    public class CreatePostViewModel
    {
        public CreatePostViewModel()
        {
            Categories = new List<int>();
        }

        [Required]
        public string Title { get; set; }

        public string Thumbnail { get; set; }

        [Required]
        public string Content { get; set; }

        public TimeSpan Created { get; set; }

        public List<int> Categories { get; set; }
    }
}

CommunityPortal/Areas/Admin/Models/ViewModels/Post/FilterPostViewModel.cs
using System.Collections.Generic;

namespace CommunityPortal.Areas.Admin.Models.ViewModels.Post
{
    public class FilterPostViewModel
    {
        public FilterPostViewModel()
        {
            Result = new List<IndexPostViewModel>();

        }

        #region Question
        
        public string Search { get; set; }

        public string Sort { get; set; }
        public string Type { get; set; }

        public int Pages { get; set; }
        public int Page { get; set; }

        #endregion

        #region Answer
        
        public List<IndexPostViewModel> Result { get; }

        #endregion
    }
}

CommunityPortal/Areas/Admin/Models/ViewModels/Post/IndexPostViewModel.cs
using System;

namespace CommunityPortal.Areas.Admin.Models.ViewModels.Post
{
    public class IndexPostViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime Created { get; set; }
    }
}

CommunityPortal/Models/Domains/Post.cs
using System;
using System.Collections.Generic;

namespace CommunityPortal.Models.Domains
{
    public class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Thumbnail { get; set; }
        public string Content { get; set; }
        public TimeSpan Created { get; set; }
        public List<CategoryPost> Categories { get; set; }
    }
}

CommunityPortal/Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using CommunityPortal.Areas.Admin.Models.Services;
using CommunityPortal.Areas.Admin.Models.ViewModels.Post;
using CommunityPortal.Models.Domains;
using CommunityPortal.Models.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace CommunityPortal.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PostController : Controller
    {
        private PostService Service { get; }
        private CategoryService CategoryService { get; }

        public PostController(PostService service, CategoryService categoryService)
        {
            Service = service;
            CategoryService = categoryService;
        }

        public IActionResult Index(FilterPostViewModel entry)
        {
            const int size = 20;

            List<Post> posts = Service.GetAll();

            if (!string.IsNullOrEmpty(entry.Search))
            {
                posts = posts.Where(item => item.Title.Contains(entry.Search)).ToList();
            }

            if (!string.IsNullOrEmpty(entry.Sort) && !string.IsNullOrEmpty(entry.Type))
            {
                if (entry.Sort.Equals(nameof(IndexPostViewModel.Id)))
                {
                    if (entry.Type.Equals("Asc"))
                    {
                        posts = posts.OrderBy(item => item.Id).ToList();
                    }
                    else if (entry.Type.Equals("Desc"))
                    {
                        posts = posts.OrderByDescending(item => item.Id).ToList();
                    }
                }
                else if (entry.Sort.Equals(nameof(IndexPostViewModel.Title)))
                {
                    if (entry.Type.Equals("Asc"))
                    {
                        posts = posts.OrderBy(item => item.Title).ToList();
                    }
                    else if (entry.Type.Equals("Desc"))
                    {
                        posts = posts.OrderByDescending(item => item.Title).ToList();
                    }
                }
                else if (entry.Sort.Equals(nameof(IndexPostViewModel.Created)))
                {
                    if (entry.Type.Equals("Asc"))
                    {
                        posts = posts.OrderBy(item => item.Created).ToList();
                    }
                    else if (entry.Type.Equals("Desc"))
                    {
                        posts = posts.OrderByDescending(item => item.Created).ToList();
                    }
                }
            }

            entry.Pages = (int)Math.Ceiling(posts.Count / (double)size);

            int offset = entry.Page > 1 ? (entry.Page - 1) * size : 0;

            entry.Result.AddRange(posts
                .Skip(offset)
                .Take(size)
                .Select(item => new IndexPostViewModel
                {
                    Id = item.Id,
                    Title = item.Title,
                    Created = DateTime.Now.Subtract(item.Created)
                })
                .ToList());


            return View(entry);
        }

        public IActionResult Create()
        {
            ViewData["Categories"] = CategoryService.GetAll();
            return View(new CreatePostViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreatePostViewModel entry)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Categories"] = CategoryService.GetAll();
                return View(entry);
            }

            Service.Add(entry);

            TempData.Message("rashin", "Your post saved successfully");

            return RedirectToAction(nameof(Index));
        }


        public IActionResult Edit(int id)
        {
            Post entry = Service.GetById(id);

            if (entry == null)
            {
                TempData.Message("rashin", "Sorry, there is a problem happened");
                return RedirectToAction(nameof(Index));
            }

            ViewData["Categories"] = CategoryService.GetAll();
            ViewBag.Id = id;

            CreatePostViewModel model = new CreatePostViewModel()
            {
                Title = entry.Title,
                Thumbnail = entry.Thumbnail,
                Content = entry.Content,
                Created = entry.Created,
                Categories = entry.Categories
                    .Select(item => item.CategoryId)
                    .ToList()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, CreatePostViewModel entry)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Categories"] = CategoryService.GetAll();
                ViewBag.Id = id;

                return View(entry);
            }

            TempData.Message("rashin",
                Service.Edit(id, entry) ? 
                    "Your post updated successfully" : 
                    "Sorry, there is a problem happened"
                );

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            TempData.Message("rashin",
                Service.Remove(id) ?
                    "Your post deleted successfully" :
                    "Sorry, there is a problem happened"
            );

            return RedirectToAction(nameof(Index));
        }
    }
}

CommunityPortal/Areas/Admin/Views/Post/Create.cshtml
@using CommunityPortal.Models.Domains
@model CreatePostViewModel

@{
    ViewData["Title"] = "Add New Post";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Add new post</h1>
</div>

<form asp-area="Admin"
      asp-controller="Post"
      asp-action="Create"
      asp-antiforgery="true">
    <div class="mb-3">
        <label asp-for="Title" class="form-label"></label>
        <input class="form-control" asp-for="Title">
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Thumbnail" class="form-label"></label>
        <input class="form-control" asp-for="Thumbnail">
        <span class="text-danger" asp-validation-for="Thumbnail"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Content" class="form-label"></label>
        <textarea class="form-control" asp-for="Content"></textarea>
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>
    @if (ViewData.ContainsKey("Categories"))
    {
        foreach (Category item in (List<Category>)ViewData["Categories"])
        {
            <div class="form-check">
                <input class="form-check-input" 
                       type="checkbox" 
                       value="@item.Id" 
                       name="Categories[]" 
                       id="Categories[@item.Id]"
                       @(Model.Categories.Any(category => category == item.Id) ? "checked" : "")>
                <label class="form-check-label" 
                       for="Categories[@item.Id]">
                    @item.Title
                </label>
            </div>
        }
    }
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

CommunityPortal/Areas/Admin/Views/Post/Edit.cshtml
@using CommunityPortal.Models.Domains
@model CreatePostViewModel

@{
    ViewData["Title"] = "Edit post";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Edit post</h1>
</div>

<form asp-area="Admin"
      asp-controller="Post"
      asp-action="Edit"
      asp-route-id="@ViewBag.Id"
      asp-antiforgery="true">
    <input type="hidden" asp-for="Created" />
    <div class="mb-3">
        <label asp-for="Title" class="form-label"></label>
        <input class="form-control" asp-for="Title">
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Thumbnail" class="form-label"></label>
        <input class="form-control" asp-for="Thumbnail">
        <span class="text-danger" asp-validation-for="Thumbnail"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Content" class="form-label"></label>
        <textarea class="form-control" asp-for="Content"></textarea>
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>
    @if (ViewData.ContainsKey("Categories"))
    {
        foreach (Category item in (List<Category>) ViewData["Categories"])
        {
            <div class="form-check">
                <input class="form-check-input"
                       type="checkbox"
                       value="@item.Id"
                       name="Categories[]"
                       id="Categories[@item.Id]"
                       @(Model.Categories.Any(category => category == item.Id) ? "checked" : "")>
                <label class="form-check-label"
                       for="Categories[@item.Id]">
                    @item.Title
                </label>
            </div>
        }
    }
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

CommunityPortal/Areas/Admin/Views/Post/Index.cshtml
@model FilterPostViewModel

@{
    ViewData["Tile"] = "Show all posts";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Show all posts</h1>
</div>

@await Component.InvokeAsync("Message")

<div class="d-flex flex-column mb-2">
    <form asp-area="Admin" asp-controller="Post" asp-action="Index"
          method="get" class="ms-auto">
        <div class="row g-3 align-items-center">
            <div class="col-auto">
                <label asp-for="Search" class="col-form-label"></label>
            </div>
            <div class="col-auto">
                <input asp-for="Search" class="form-control" />
            </div>
            <div class="col-auto">
                <button class="btn btn-primary" type="submit">Search</button>
            </div>
        </div>
    </form>
</div>

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    <a asp-area="Admin"
                       asp-controller="Post"
                       asp-action="Index"
                       asp-route-Sort="Id"
                       asp-route-Type="@(
    !string.IsNullOrEmpty(Model.Sort) && Model.Sort.Equals("Id") ?
        (Model.Type.Equals("Asc") ? "Desc" : "Asc" ) :
        "Asc"
                                           )"
                       asp-route-Search="@Model.Search">
                        #
                    </a>
                </th>
                <th>
                    <a asp-area="Admin"
                       asp-controller="Post"
                       asp-action="Index"
                       asp-route-Sort="Title"
                       asp-route-Type="@(
    !string.IsNullOrEmpty(Model.Sort) && Model.Sort.Equals("Title") ?
        (Model.Type.Equals("Asc") ? "Desc" : "Asc" ) :
        "Asc"
                                           )"
                       asp-route-Search="@Model.Search">
                        Title
                    </a>
                </th>
                <th>
                    <a asp-area="Admin"
                       asp-controller="Post"
                       asp-action="Index"
                       asp-route-Sort="Created"
                       asp-route-Type="@(
    !string.IsNullOrEmpty(Model.Sort) && Model.Sort.Equals("Created") ?
        (Model.Type.Equals("Asc") ? "Desc" : "Asc" ) :
        "Asc"
                                           )"
                       asp-route-Search="@Model.Search">
                        Created
                    </a>
                </th>
                <th>
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Result.Count != 0)
            {
                @foreach (IndexPostViewModel item in Model.Result)
                {
                    <tr>
                        <td>
                            @item.Id
                        </td>
                        <td>
                            @item.Title
                        </td>
                        <td>
                            @item.Created
                        </td>
                        <td>
                            <a class="btn btn-link text-info"
                               asp-area="Admin"
                               asp-controller="Post"
                               asp-action="Edit"
                               asp-route-id="@item.Id">
                                Edit
                            </a>
                            <a class="btn btn-link text-danger"
                               asp-area="Admin"
                               asp-controller="Post"
                               asp-action="Delete"
                               asp-route-id="@item.Id">
                                Delete
                            </a>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="4">
                        <p>There is no post for showing</p>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>